"""Symphony 的 init 命令 - 交互式设置向导。"""

from __future__ import annotations

import os
import re
from pathlib import Path

import click
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm, Prompt
from rich.text import Text

console = Console()

# WORKFLOW.md 模板
WORKFLOW_TEMPLATE = '''---
symphony:
  version: "1.0"
  
  settings:
    # LLM Configuration
    llm:
      # Supported: openai, anthropic, deepseek, gemini, azure
      provider: {provider}
      model: {model}
      # Optional: custom base URL (for proxies or self-hosted)
      # base_url: https://api.example.com/v1
      temperature: 0.7
      max_tokens: 4096
    
    # Agent Configuration
    agent:
      max_turns: 20
      # File patterns to include in workspace context
      include_patterns:
        - "**/*.py"
        - "**/*.js"
        - "**/*.ts"
        - "**/*.md"
      # File patterns to exclude
      exclude_patterns:
        - "**/.git/**"
        - "**/node_modules/**"
        - "**/__pycache__/**"
        - "**/.venv/**"
        - "**/venv/**"
    
    # Linear Integration
    tracker:
      kind: linear
      endpoint: https://api.linear.app/graphql
      project_slug: {project_slug}
      # Linear team states that indicate an issue is ready to be worked on
      active_states:
        - "Todo"
        - "In Progress"
      # Linear team states that indicate an issue is completed
      terminal_states:
        - "Done"
        - "Canceled"
    
    # Workspace Configuration
    workspace:
      root: ./workspaces
      max_concurrent_agents: 3
    
    # Lifecycle Hooks
    hooks:
      timeout_ms: 30000
      after_create: |
        echo "Workspace created for $SYMPHONY_ISSUE_ID"
      before_run: |
        echo "Starting work on $SYMPHONY_ISSUE_ID"
      after_run: |
        echo "Completed work on $SYMPHONY_ISSUE_ID"
      before_remove: |
        echo "Cleaning up workspace for $SYMPHONY_ISSUE_ID"

  # Prompt Template
  prompt: |
    You are working on Linear issue {{identifier}}: {{title}}
    
    Description:
    {{{{description}}}}
    
    Labels: {{{{labels|join(', ')}}}}
    Blocked by: {{{{blockers|join(', ')}}}}
    
    Your task is to:
    1. Understand the requirements
    2. Explore the codebase if needed
    3. Implement the necessary changes
    4. Test your changes
    5. Provide a summary of what was done
    
    {{#if attempt}}
    This is attempt {{attempt}}. Previous attempt failed, please review and fix.
    {{/if}}
    
    {{#if workspace}}
    Workspace: {{workspace}}
    {{/if}}
---

# Symphony Workflow

This project uses [Symphony](https://github.com/openai/symphony) for automated agent orchestration.

## Quick Start

1. Configure environment variables in `.env`
2. Run: `symphony WORKFLOW.md`

## Available Tools

- `read_file` - Read files in workspace
- `write_file` - Write files in workspace  
- `execute_command` - Run shell commands
- `linear_graphql` - Query Linear API
- `add_comment` - Add comments to Linear issues
'''

# .env 文件模板
ENV_TEMPLATE = '''# Symphony Environment Configuration
# Generated by `symphony init`

# ============================================
# LLM Provider Configuration
# ============================================

# OpenAI (Default)
OPENAI_API_KEY={openai_key}
OPENAI_BASE_URL=https://api.openai.com/v1
OPENAI_MODEL=gpt-4

# Anthropic (Alternative)
# ANTHROPIC_API_KEY=your_key_here
# ANTHROPIC_MODEL=claude-3-sonnet-20240229

# DeepSeek (Alternative)
# DEEPSEEK_API_KEY=your_key_here
# DEEPSEEK_MODEL=deepseek-chat

# Gemini (Alternative)
# GEMINI_API_KEY=your_key_here
# GEMINI_MODEL=gemini-pro

# ============================================
# Linear Configuration
# ============================================

LINEAR_API_KEY={linear_key}
LINEAR_PROJECT_SLUG={project_slug}

# ============================================
# Symphony Settings
# ============================================

SYMPHONY_LOG_LEVEL=INFO
SYMPHONY_MAX_CONCURRENT=3
'''


@click.command(name="init")
@click.option(
    "--path",
    "-p",
    type=click.Path(path_type=Path),
    default=".",
    help="Directory to initialize Symphony in",
)
@click.option(
    "--force",
    "-f",
    is_flag=True,
    help="Overwrite existing files",
)
def init_command(path: Path, force: bool) -> None:
    """在当前目录初始化 Symphony。
    
    创建 WORKFLOW.md 和 .env 文件，并交互式配置。
    """
    console.print(Panel.fit(
        "[bold cyan]🎼 Symphony Initialization Wizard[/bold cyan]\n"
        "Let's set up Symphony for your project!",
        border_style="cyan"
    ))
    
    path = path.resolve()
    
    # 检查现有文件
    workflow_file = path / "WORKFLOW.md"
    env_file = path / ".env"
    
    if workflow_file.exists() and not force:
        if not Confirm.ask(
            f"[yellow]WORKFLOW.md already exists. Overwrite?[/yellow]",
            default=False
        ):
            console.print("[dim]Skipping WORKFLOW.md[/dim]")
            return
    
    console.print("\n[bold]Step 1: LLM Provider Configuration[/bold]")
    
    # LLM 提供商选择
    provider = Prompt.ask(
        "Select LLM provider",
        choices=["openai", "anthropic", "deepseek", "gemini"],
        default="openai"
    )
    
    # 基于提供商的模型选择
    model_defaults = {
        "openai": "gpt-4",
        "anthropic": "claude-3-sonnet-20240229",
        "deepseek": "deepseek-chat",
        "gemini": "gemini-pro",
    }
    
    model = Prompt.ask(
        "Model name",
        default=model_defaults[provider]
    )
    
    # API 密钥
    api_key_env = f"{provider.upper()}_API_KEY"
    existing_key = os.environ.get(api_key_env, "")
    
    if existing_key:
        masked = existing_key[:8] + "..." + existing_key[-4:] if len(existing_key) > 12 else "***"
        use_existing = Confirm.ask(
            f"Found {api_key_env}={masked}. Use this key?",
            default=True
        )
        api_key = existing_key if use_existing else ""
    else:
        api_key = ""
    
    if not api_key:
        api_key = Prompt.ask(
            f"Enter your {provider.upper()} API key",
            password=True
        )
    
    console.print("\n[bold]Step 2: Linear Integration[/bold]")
    
    # Linear 配置
    linear_key = os.environ.get("LINEAR_API_KEY", "")
    if linear_key:
        masked = linear_key[:4] + "..." if len(linear_key) > 8 else "***"
        use_existing = Confirm.ask(
            f"Found LINEAR_API_KEY={masked}. Use this key?",
            default=True
        )
        if not use_existing:
            linear_key = Prompt.ask("Enter your Linear API key", password=True)
    else:
        linear_key = Prompt.ask("Enter your Linear API key (optional)", password=True, default="")
    
    project_slug = Prompt.ask(
        "Linear project slug",
        default=os.environ.get("LINEAR_PROJECT_SLUG", "my-project")
    )
    
    console.print("\n[bold]Step 3: Advanced Settings[/bold]")
    
    max_concurrent = Prompt.ask(
        "Maximum concurrent agents",
        default="3"
    )
    
    # 生成文件
    console.print("\n[bold]Generating configuration files...[/bold]")
    
    # 创建 WORKFLOW.md
    workflow_content = WORKFLOW_TEMPLATE.format(
        provider=provider,
        model=model,
        project_slug=project_slug,
    )
    
    workflow_file.write_text(workflow_content)
    console.print(f"  [green]✓[/green] Created {workflow_file}")
    
    # 创建 .env
    env_content = ENV_TEMPLATE.format(
        openai_key=api_key if provider == "openai" else "",
        linear_key=linear_key,
        project_slug=project_slug,
    )
    
    # 根据提供商调整环境文件
    if provider != "openai":
        env_lines = env_content.split("\n")
        new_lines = []
        skip_openai = False
        for line in env_lines:
            if "OPENAI_API_KEY" in line and provider != "openai":
                new_lines.append(f"# {line}")
            elif f"{provider.upper()}_API_KEY" in line:
                new_lines.append(f"{provider.upper()}_API_KEY={api_key}")
            else:
                new_lines.append(line)
        env_content = "\n".join(new_lines)
    
    if not env_file.exists() or force:
        env_file.write_text(env_content)
        console.print(f"  [green]✓[/green] Created {env_file}")
    else:
        console.print(f"  [yellow]⚠[/yellow] {env_file} already exists, skipping")
    
    # 创建 .env.example
    env_example = path / ".env.example"
    if not env_example.exists() or force:
        env_example.write_text(env_content.replace(api_key, "your_api_key_here"))
        console.print(f"  [green]✓[/green] Created {env_example}")
    
    console.print("\n" + Panel.fit(
        "[bold green]✓ Symphony initialized successfully![/bold green]\n\n"
        f"[bold]Next steps:[/bold]\n"
        f"1. Review [cyan]{workflow_file.name}[/cyan] and customize settings\n"
        f"2. Edit [cyan]{env_file.name}[/cyan] with your API keys\n"
        f"3. Run: [cyan]symphony {workflow_file.name}[/cyan]\n\n"
        f"[dim]For help: symphony --help[/dim]",
        border_style="green"
    ))
